---
- hosts: all
  become: yes
  tasks:
  - name: i want install apache2 on ubuntu server
    apt:
     name: apache2
     state: present
     
  - name: i want start webserver on ubuntu server
    service:
      name: apache2
      state: started
